/* Rivaayat — independent jewellers marketplace
   All catalogue, shop and rate data lives here (plus localStorage overlays). */

const RIVAAYAT = {
  brand: {
    name: "Rivaayat",
    mark: "R",
    tagline: "Independent jewellers. Direct to you.",
    city: "Bhopal",
    supportEmail: "developersoftware.support@gmail.com",
    phone: "+91 755 401 2200",
    address: "3rd Floor, Heritage Arcade, New Market, TT Nagar, Bhopal 462003",
  },

  /* Indicative city rates for 20 Aug 2026. Banner updates from this object. */
  rates: {
    date: "20 August 2026",
    city: "Bhopal",
    gstMetal: 3,
    gstMaking: 5,
    hallmark: 45,
    metals: {
      "24K": { label: "24K Gold", perGram: 15927, prev: 15497, unit: "g" },
      "22K": { label: "22K Gold", perGram: 14600, prev: 14205, unit: "g" },
      "18K": { label: "18K Gold", perGram: 11946, prev: 11623, unit: "g" },
      Silver: { label: "Silver", perGram: 255, prev: 245, unit: "g" },
      Platinum: { label: "Platinum", perGram: 4820, prev: 4755, unit: "g" },
    },
  },

  themes: [
    {
      id: "heritage",
      name: "Heritage Gold",
      subtitle: "Temple, kundan and classic 22K",
      desc: "Deep wine walls, gold borders and serif type — built for family jewellers who sell tradition.",
    },
    {
      id: "lumina",
      name: "Lumina Diamond",
      subtitle: "Solitaires, platinum and night sparkle",
      desc: "Black velvet, ice-white type and diamond-cut grids — for diamond boutiques.",
    },
    {
      id: "suhag",
      name: "Suhag Bridal",
      subtitle: "Trousseau, polki and wedding sets",
      desc: "Blush silk, rose-gold lines and editorial portraits — for bridal ateliers.",
    },
    {
      id: "noor",
      name: "Noor Contemporary",
      subtitle: "Daily wear, light gold and silver",
      desc: "Ivory space, champagne metal and quiet photography — for modern studios.",
    },
  ],

  categories: [
    { id: "gold", name: "Gold", image: "assets/cat-gold.png", blurb: "Hallmarked 18K · 22K · 24K" },
    { id: "diamond", name: "Diamond", image: "assets/cat-diamond.png", blurb: "Solitaires & everyday sparkle" },
    { id: "bridal", name: "Bridal", image: "assets/cat-bridal.png", blurb: "Complete trousseau sets" },
    { id: "polki", name: "Polki", image: "assets/cat-polki.png", blurb: "Uncut diamonds, royal finish" },
    { id: "silver", name: "Silver", image: "assets/cat-silver.png", blurb: "Temple, oxidised & daily" },
    { id: "temple", name: "Temple", image: "assets/prod-temple-haar.png", blurb: "Deity motifs & antique work" },
  ],

  types: ["Necklace", "Earrings", "Bangles", "Rings", "Pendant", "Set", "Nath", "Anklet", "Bracelet"],
  occasions: ["Daily Wear", "Wedding", "Festive", "Office", "Gift"],
  purities: ["18K", "22K", "24K", "Silver", "Platinum"],

  shops: [
    {
      id: "kanakshree",
      name: "Kanakshree Jewellers",
      area: "New Market, TT Nagar",
      city: "Bhopal",
      address: "Shop 14–15, Counter Market, New Market, TT Nagar, Bhopal 462003",
      phone: "+91 755 401 2214",
      whatsapp: "917554012214",
      email: "kanakshree@rivaayat.in",
      since: 1986,
      specialty: ["Gold", "Temple", "Bridal"],
      theme: "heritage",
      rating: 4.8,
      reviews: 312,
      verified: true,
      makingPct: 12,
      wastagePct: 2,
      hours: "10:30 AM – 8:30 PM",
      about: "Three-generation goldsmiths known for temple haars and tight making on 22K daily wear.",
      highlights: ["BIS Hallmark", "Old-gold exchange", "On-spot sizing"],
    },
    {
      id: "noormahal",
      name: "Noor Mahal Diamonds",
      area: "10 No. Market, Arera Colony",
      city: "Bhopal",
      address: "E-4, 10 Number Market, near Croma, Arera Colony, Bhopal 462016",
      phone: "+91 755 401 2288",
      whatsapp: "917554012288",
      email: "noormahal@rivaayat.in",
      since: 2004,
      specialty: ["Diamond", "Platinum", "Rings"],
      theme: "lumina",
      rating: 4.9,
      reviews: 428,
      verified: true,
      makingPct: 16,
      wastagePct: 1,
      hours: "11:00 AM – 9:00 PM",
      about: "Certified solitaires and light diamond jewellery with IGI reports on every centre stone.",
      highlights: ["IGI certified", "Buyback 90%", "Private viewing lounge"],
    },
    {
      id: "mandakini",
      name: "Mandakini Gold House",
      area: "Mandakini Square, Kolar Road",
      city: "Bhopal",
      address: "Shop 2, Shivashish Complex, Mandakini Square, Kolar Road, Bhopal 462042",
      phone: "+91 755 401 2302",
      whatsapp: "917554012302",
      email: "mandakini@rivaayat.in",
      since: 1999,
      specialty: ["Gold", "Daily Wear", "Chains"],
      theme: "noor",
      rating: 4.7,
      reviews: 186,
      verified: true,
      makingPct: 10,
      wastagePct: 1.5,
      hours: "10:00 AM – 9:00 PM",
      about: "Machine and handmade chains with some of the lowest making on lightweight 22K in the city.",
      highlights: ["Low making", "Same-day repair", "Parking"],
    },
    {
      id: "sarafaghar",
      name: "Sarafa Ghar Itwara",
      area: "Sarafa Chowk, Itwara",
      city: "Bhopal",
      address: "Lane 3, Sarafa Chowk, Itwara, Bhopal 462001",
      phone: "+91 755 401 2190",
      whatsapp: "917554012190",
      email: "sarafaghar@rivaayat.in",
      since: 1972,
      specialty: ["Gold", "Silver", "Coins"],
      theme: "heritage",
      rating: 4.6,
      reviews: 254,
      verified: true,
      makingPct: 11,
      wastagePct: 2,
      hours: "10:00 AM – 8:00 PM  ·  Closed Tuesday",
      about: "A chowk workshop that still casts in-house. Honest rates, no showroom theatre.",
      highlights: ["In-house casting", "Silver payal", "Gold coins"],
    },
    {
      id: "rajwada",
      name: "Rajwada Bridal Atelier",
      area: "MP Nagar Zone II",
      city: "Bhopal",
      address: "Plot 21, Zone II, Maharana Pratap Nagar, Bhopal 462011",
      phone: "+91 755 401 2401",
      whatsapp: "917554012401",
      email: "rajwada@rivaayat.in",
      since: 2011,
      specialty: ["Bridal", "Polki", "Kundan"],
      theme: "suhag",
      rating: 4.9,
      reviews: 391,
      verified: true,
      makingPct: 22,
      wastagePct: 3,
      hours: "11:00 AM – 8:30 PM  ·  Appointment preferred",
      about: "Trousseau specialists. Full sets styled on the bride, with trial jewellery for the pheras.",
      highlights: ["Trial jewellery", "Family portraits", "Custom mehendi sets"],
    },
    {
      id: "chandrahaas",
      name: "Chandrahaas Polki Studio",
      area: "Gulmohar Colony",
      city: "Bhopal",
      address: "12, Gulmohar Extension, Bhopal 462039",
      phone: "+91 755 401 2515",
      whatsapp: "917554012515",
      email: "chandrahaas@rivaayat.in",
      since: 2008,
      specialty: ["Polki", "Kundan", "Earrings"],
      theme: "heritage",
      rating: 4.8,
      reviews: 167,
      verified: true,
      makingPct: 20,
      wastagePct: 2.5,
      hours: "11:00 AM – 8:00 PM",
      about: "Uncut diamond work finished in Jaipur karigars, set in 22K for Bhopal families.",
      highlights: ["Jaipur karigars", "Polki reset", "Antique finish"],
    },
    {
      id: "sonasutra",
      name: "Sona Sutra",
      area: "Bittan Market, Arera Colony",
      city: "Bhopal",
      address: "Link Road 3, E-5 Bittan Market, Arera Colony, Bhopal 462016",
      phone: "+91 755 401 2611",
      whatsapp: "917554012611",
      email: "sonasutra@rivaayat.in",
      since: 2016,
      specialty: ["Gold", "Office", "Lightweight"],
      theme: "noor",
      rating: 4.5,
      reviews: 98,
      verified: true,
      makingPct: 14,
      wastagePct: 1,
      hours: "11:00 AM – 8:30 PM",
      about: "Light 18K and 22K for working women — hoops, pendants and everyday chains.",
      highlights: ["Under 8 grams", "Workwear edit", "Gift wrap"],
    },
    {
      id: "aabharan",
      name: "Aabharan Craft House",
      area: "Kolar Road",
      city: "Bhopal",
      address: "Sector A, near Mandakini Square, Kolar Road, Bhopal 462042",
      phone: "+91 755 401 2720",
      whatsapp: "917554012720",
      email: "aabharan@rivaayat.in",
      since: 2013,
      specialty: ["Designer", "Diamond", "Gold"],
      theme: "lumina",
      rating: 4.7,
      reviews: 143,
      verified: true,
      makingPct: 18,
      wastagePct: 2,
      hours: "11:00 AM – 9:00 PM",
      about: "Independent designers who will sketch a piece with you and cast it in four weeks.",
      highlights: ["Custom CAD", "4-week make", "Sketch sitting"],
    },
    {
      id: "meenakshi",
      name: "Meenakshi Silver Works",
      area: "New Market, TT Nagar",
      city: "Bhopal",
      address: "Stall 8, Counter Market, New Market, Bhopal 462003",
      phone: "+91 755 401 2804",
      whatsapp: "917554012804",
      email: "meenakshi@rivaayat.in",
      since: 1994,
      specialty: ["Silver", "Temple", "Anklets"],
      theme: "noor",
      rating: 4.6,
      reviews: 121,
      verified: true,
      makingPct: 25,
      wastagePct: 0,
      hours: "10:30 AM – 8:30 PM",
      about: "Oxidised temple silver, payals and household silver with transparent per-gram making.",
      highlights: ["92.5 silver", "Oxidised restore", "Pooja articles"],
    },
    {
      id: "hiravatika",
      name: "Hira Vatika",
      area: "Arera Colony",
      city: "Bhopal",
      address: "E-3/12, Arera Colony, Bhopal 462016",
      phone: "+91 755 401 2918",
      whatsapp: "917554012918",
      email: "hiravatika@rivaayat.in",
      since: 2001,
      specialty: ["Diamond", "Bracelet", "Earrings"],
      theme: "lumina",
      rating: 4.8,
      reviews: 205,
      verified: true,
      makingPct: 15,
      wastagePct: 1,
      hours: "11:00 AM – 8:30 PM",
      about: "Tennis lines, studs and everyday diamonds with published stone charts on every invoice.",
      highlights: ["Stone chart", "Lifetime polish", "Insurance help"],
    },
    {
      id: "shringar",
      name: "Shringar Nath Studio",
      area: "10 No. Market, Arera Colony",
      city: "Bhopal",
      address: "Upper floor, 10 Number Market, Arera Colony, Bhopal 462016",
      phone: "+91 755 401 3011",
      whatsapp: "917554013011",
      email: "shringar@rivaayat.in",
      since: 2009,
      specialty: ["Nath", "Maang Tikka", "Bridal"],
      theme: "suhag",
      rating: 4.7,
      reviews: 88,
      verified: true,
      makingPct: 18,
      wastagePct: 2,
      hours: "11:30 AM – 8:00 PM",
      about: "Nose rings, hathphools and matha pattis made to the bride's facial measurements.",
      highlights: ["Face mapping", "Clip-on naths", "Pearl restring"],
    },
    {
      id: "balsona",
      name: "Bal Sona",
      area: "TT Nagar",
      city: "Bhopal",
      address: "Near Music Mahal, New Market, TT Nagar, Bhopal 462003",
      phone: "+91 755 401 3119",
      whatsapp: "917554013119",
      email: "balsona@rivaayat.in",
      since: 1997,
      specialty: ["Kids", "Gold", "Gift"],
      theme: "noor",
      rating: 4.5,
      reviews: 76,
      verified: true,
      makingPct: 13,
      wastagePct: 1,
      hours: "10:30 AM – 8:00 PM",
      about: "Lightweight baby bangles, nazariyas and first-gold gifts with extra-smooth finishing.",
      highlights: ["Hypoallergenic", "Gift boxes", "Resizing till age 12"],
    },
  ],

  products: [
    {
      id: "p01",
      name: "Lakshmi Temple Haar",
      shopId: "kanakshree",
      category: "temple",
      type: "Necklace",
      metal: "Gold",
      purity: "22K",
      weight: 48.6,
      makingPct: 14,
      wastagePct: 2.5,
      stoneCharges: 12500,
      occasion: "Festive",
      gender: "Women",
      bestseller: true,
      featured: true,
      image: "assets/prod-temple-haar.png",
      description: "Long 22K haar with goddess plaques, ruby kundan and green meenakari. Cast in-house at Kanakshree.",
    },
    {
      id: "p02",
      name: "Pearl Dome Jhumkas",
      shopId: "kanakshree",
      category: "gold",
      type: "Earrings",
      metal: "Gold",
      purity: "22K",
      weight: 12.4,
      makingPct: 16,
      wastagePct: 2,
      stoneCharges: 2800,
      occasion: "Festive",
      gender: "Women",
      bestseller: true,
      featured: true,
      image: "assets/prod-gold-jhumka.png",
      description: "Classic dome jhumkas with seed pearls. Screw backs, comfortable for all-day wear.",
    },
    {
      id: "p03",
      name: "Black-Bead Diamond Mangalsutra",
      shopId: "noormahal",
      category: "diamond",
      type: "Necklace",
      metal: "Gold",
      purity: "18K",
      weight: 8.2,
      makingPct: 18,
      wastagePct: 1,
      stoneCharges: 42000,
      occasion: "Daily Wear",
      gender: "Women",
      bestseller: true,
      featured: true,
      image: "assets/prod-mangalsutra.png",
      description: "18K chain, black beads and a round-brilliant pendant. IGI card included.",
    },
    {
      id: "p04",
      name: "Peacock Kada Pair",
      shopId: "sarafaghar",
      category: "gold",
      type: "Bangles",
      metal: "Gold",
      purity: "22K",
      weight: 36.8,
      makingPct: 11,
      wastagePct: 2,
      stoneCharges: 0,
      occasion: "Wedding",
      gender: "Women",
      bestseller: true,
      featured: false,
      image: "assets/prod-gold-kada.png",
      description: "Openable kadas with hand-engraved peacocks. Making kept close to chowk workshop rates.",
    },
    {
      id: "p05",
      name: "Ice Line Diamond Necklace",
      shopId: "hiravatika",
      category: "diamond",
      type: "Necklace",
      metal: "Gold",
      purity: "18K",
      weight: 14.1,
      makingPct: 15,
      wastagePct: 1,
      stoneCharges: 185000,
      occasion: "Office",
      gender: "Women",
      bestseller: true,
      featured: true,
      image: "assets/prod-diamond-necklace.png",
      description: "White-gold illusion necklace. Stone chart printed on the invoice.",
    },
    {
      id: "p06",
      name: "Brilliant Studs 0.80 ct tw",
      shopId: "noormahal",
      category: "diamond",
      type: "Earrings",
      metal: "Gold",
      purity: "18K",
      weight: 3.1,
      makingPct: 16,
      wastagePct: 1,
      stoneCharges: 98000,
      occasion: "Daily Wear",
      gender: "Women",
      bestseller: true,
      featured: false,
      image: "assets/prod-diamond-studs.png",
      description: "Matched round brilliants, screw backs, lifetime polish.",
    },
    {
      id: "p07",
      name: "Kundan Maang Tikka",
      shopId: "shringar",
      category: "bridal",
      type: "Pendant",
      metal: "Gold",
      purity: "22K",
      weight: 9.6,
      makingPct: 18,
      wastagePct: 2,
      stoneCharges: 6400,
      occasion: "Wedding",
      gender: "Women",
      bestseller: false,
      featured: true,
      image: "assets/prod-maang-tikka.png",
      description: "Matha patti tikka with kundan and pearl drops. Sized to the bride's hairline.",
    },
    {
      id: "p08",
      name: "Daily 22K Rope Chain",
      shopId: "mandakini",
      category: "gold",
      type: "Necklace",
      metal: "Gold",
      purity: "22K",
      weight: 10.0,
      makingPct: 8,
      wastagePct: 1,
      stoneCharges: 0,
      occasion: "Daily Wear",
      gender: "Unisex",
      bestseller: true,
      featured: false,
      image: "assets/prod-gold-chain.png",
      description: "Machine-made rope chain. Among the lowest making on the platform.",
    },
    {
      id: "p09",
      name: "Rose Cocktail Ring",
      shopId: "aabharan",
      category: "diamond",
      type: "Rings",
      metal: "Gold",
      purity: "18K",
      weight: 5.4,
      makingPct: 20,
      wastagePct: 1,
      stoneCharges: 56000,
      occasion: "Gift",
      gender: "Women",
      bestseller: false,
      featured: true,
      image: "assets/prod-rose-ring.png",
      description: "Rose-gold shank, oval centre, diamond halo. CAD sitting available.",
    },
    {
      id: "p10",
      name: "Rajwada Bridal Ensemble",
      shopId: "rajwada",
      category: "bridal",
      type: "Set",
      metal: "Gold",
      purity: "22K",
      weight: 86.0,
      makingPct: 22,
      wastagePct: 3,
      stoneCharges: 48000,
      occasion: "Wedding",
      gender: "Women",
      bestseller: true,
      featured: true,
      image: "assets/prod-bridal-set.png",
      description: "Necklace, earrings, matha patti. Trial jewellery included for pheras.",
    },
    {
      id: "p11",
      name: "Pearl Nath",
      shopId: "shringar",
      category: "bridal",
      type: "Nath",
      metal: "Gold",
      purity: "22K",
      weight: 4.2,
      makingPct: 18,
      wastagePct: 2,
      stoneCharges: 1800,
      occasion: "Wedding",
      gender: "Women",
      bestseller: false,
      featured: false,
      image: "assets/prod-nath.png",
      description: "Clip-on or pierced. Pearl and ruby. Face-mapped at the studio.",
    },
    {
      id: "p12",
      name: "Gentleman Cluster Ring",
      shopId: "noormahal",
      category: "diamond",
      type: "Rings",
      metal: "Gold",
      purity: "18K",
      weight: 7.8,
      makingPct: 16,
      wastagePct: 1,
      stoneCharges: 72000,
      occasion: "Office",
      gender: "Men",
      bestseller: false,
      featured: false,
      image: "assets/prod-mens-ring.png",
      description: "Heavy 18K men's ring with rectangular diamond cluster.",
    },
    {
      id: "p13",
      name: "Baby Bell Bangles",
      shopId: "balsona",
      category: "gold",
      type: "Bangles",
      metal: "Gold",
      purity: "22K",
      weight: 6.8,
      makingPct: 13,
      wastagePct: 1,
      stoneCharges: 0,
      occasion: "Gift",
      gender: "Kids",
      bestseller: true,
      featured: false,
      image: "assets/prod-kids-bangles.png",
      description: "Smooth 22K baby bangles with tiny ghungroos. Resizing till age 12.",
    },
    {
      id: "p14",
      name: "Ghungroo Silver Payal",
      shopId: "meenakshi",
      category: "silver",
      type: "Anklet",
      metal: "Silver",
      purity: "Silver",
      weight: 42.0,
      makingPct: 25,
      wastagePct: 0,
      stoneCharges: 0,
      occasion: "Daily Wear",
      gender: "Women",
      bestseller: true,
      featured: false,
      image: "assets/prod-silver-payal.png",
      description: "92.5 silver payal, oxidised and polish mix, adjustable chain.",
    },
    {
      id: "p15",
      name: "Diamond Line Hoops",
      shopId: "sonasutra",
      category: "gold",
      type: "Earrings",
      metal: "Gold",
      purity: "18K",
      weight: 4.6,
      makingPct: 14,
      wastagePct: 1,
      stoneCharges: 18500,
      occasion: "Office",
      gender: "Women",
      bestseller: false,
      featured: true,
      image: "assets/prod-gold-hoops.png",
      description: "Light 18K hoops with a diamond line. Made for workwear.",
    },
    {
      id: "p16",
      name: "Devi Enamel Pendant",
      shopId: "kanakshree",
      category: "temple",
      type: "Pendant",
      metal: "Gold",
      purity: "22K",
      weight: 5.9,
      makingPct: 15,
      wastagePct: 2,
      stoneCharges: 2200,
      occasion: "Festive",
      gender: "Women",
      bestseller: false,
      featured: false,
      image: "assets/prod-goddess-pendant.png",
      description: "Green meenakari goddess plaque on a fine chain.",
    },
    {
      id: "p17",
      name: "Chandbali Polki Earrings",
      shopId: "chandrahaas",
      category: "polki",
      type: "Earrings",
      metal: "Gold",
      purity: "22K",
      weight: 18.2,
      makingPct: 20,
      wastagePct: 2.5,
      stoneCharges: 34000,
      occasion: "Wedding",
      gender: "Women",
      bestseller: true,
      featured: true,
      image: "assets/prod-chandbali.png",
      description: "Jaipur-set uncut diamonds, pearl fringe, antique gold.",
    },
    {
      id: "p18",
      name: "Hathphool Hand Harness",
      shopId: "rajwada",
      category: "bridal",
      type: "Bracelet",
      metal: "Gold",
      purity: "22K",
      weight: 22.4,
      makingPct: 22,
      wastagePct: 3,
      stoneCharges: 8900,
      occasion: "Wedding",
      gender: "Women",
      bestseller: false,
      featured: false,
      image: "assets/prod-hathphool.png",
      description: "Ring-to-wrist bridal harness in kundan. Pair available.",
    },
    {
      id: "p19",
      name: "Office Teardrop Necklace",
      shopId: "sonasutra",
      category: "gold",
      type: "Necklace",
      metal: "Gold",
      purity: "22K",
      weight: 7.3,
      makingPct: 14,
      wastagePct: 1,
      stoneCharges: 4500,
      occasion: "Office",
      gender: "Women",
      bestseller: false,
      featured: true,
      image: "assets/prod-daily-necklace.png",
      description: "Under-eight-gram 22K necklace with a single teardrop.",
    },
    {
      id: "p20",
      name: "Tennis Diamond Bracelet",
      shopId: "hiravatika",
      category: "diamond",
      type: "Bracelet",
      metal: "Gold",
      purity: "18K",
      weight: 11.6,
      makingPct: 15,
      wastagePct: 1,
      stoneCharges: 210000,
      occasion: "Gift",
      gender: "Women",
      bestseller: true,
      featured: false,
      image: "assets/prod-diamond-bracelet.png",
      description: "Line bracelet, matched colour and clarity, clasp lock.",
    },
    {
      id: "p21",
      name: "Bichhiya Toe Rings",
      shopId: "meenakshi",
      category: "silver",
      type: "Rings",
      metal: "Silver",
      purity: "Silver",
      weight: 8.5,
      makingPct: 25,
      wastagePct: 0,
      stoneCharges: 0,
      occasion: "Daily Wear",
      gender: "Women",
      bestseller: false,
      featured: false,
      image: "assets/prod-bichhiya.png",
      description: "Adjustable 92.5 silver toe rings with tiny bells.",
    },
    {
      id: "p22",
      name: "Polki Choker",
      shopId: "chandrahaas",
      category: "polki",
      type: "Necklace",
      metal: "Gold",
      purity: "22K",
      weight: 41.0,
      makingPct: 20,
      wastagePct: 2.5,
      stoneCharges: 76000,
      occasion: "Wedding",
      gender: "Women",
      bestseller: true,
      featured: true,
      image: "assets/cat-polki.png",
      description: "Close-set uncut diamond choker with emerald drops.",
    },
    {
      id: "p23",
      name: "Floral Meena Bangle Stack",
      shopId: "mandakini",
      category: "gold",
      type: "Bangles",
      metal: "Gold",
      purity: "22K",
      weight: 28.5,
      makingPct: 12,
      wastagePct: 1.5,
      stoneCharges: 3200,
      occasion: "Festive",
      gender: "Women",
      bestseller: false,
      featured: true,
      image: "assets/cat-gold.png",
      description: "Set of floral meenakari bangles. Mix and match diameters.",
    },
    {
      id: "p24",
      name: "Solitaire Ring 0.50 ct",
      shopId: "noormahal",
      category: "diamond",
      type: "Rings",
      metal: "Gold",
      purity: "Platinum",
      weight: 4.8,
      makingPct: 16,
      wastagePct: 0,
      stoneCharges: 145000,
      occasion: "Gift",
      gender: "Women",
      bestseller: true,
      featured: true,
      image: "assets/cat-diamond.png",
      description: "Platinum setting, IGI 0.50 ct centre. Private viewing on request.",
    },
  ],

  testimonials: [
    {
      name: "Ananya Sharma",
      area: "Arera Colony",
      text: "Ordered the ice-line necklace from Noor Mahal through Rivaayat. The shop called the same evening with the stone chart. Felt like a private appointment, not an app.",
      rating: 5,
    },
    {
      name: "Farhan Qureshi",
      area: "Kolar Road",
      text: "Used the calculator against Mandakini's making before walking in. The bill matched to the rupee. That is why we keep coming.",
      rating: 5,
    },
    {
      name: "Meera Joshi",
      area: "MP Nagar",
      text: "Rajwada styled the full bridal set on me, then confirmed the order online. Making and GST were itemised. No last-minute surprises.",
      rating: 5,
    },
    {
      name: "Sneha Iyer",
      area: "TT Nagar",
      text: "Kanakshree's temple haar is the piece I wear to every family wedding. Hallmark, weight and making were all on the invoice.",
      rating: 4,
    },
  ],

  reviews: {
    kanakshree: [
      { name: "Ritika M.", rating: 5, text: "Temple haar finishing is museum-grade. Staff explained GST lines without rushing." },
      { name: "Vivek S.", rating: 5, text: "Old gold exchange was fair. New Market parking is the only hassle." },
      { name: "Pooja T.", rating: 4, text: "Jhumkas are lighter than they look. Took one extra day for screw-back conversion." },
    ],
    noormahal: [
      { name: "Ayesha K.", rating: 5, text: "IGI card handed over before billing. Lounge is quiet — good for solitaire decisions." },
      { name: "Nikhil R.", rating: 5, text: "Men's cluster ring sized in 40 minutes. Buyback terms printed, not verbal." },
      { name: "Sana P.", rating: 4, text: "Prices sit at the higher end, but the stone matching is honest." },
    ],
    mandakini: [
      { name: "Deepa L.", rating: 5, text: "Lowest making I have seen on a 10 g rope chain in Bhopal." },
      { name: "Imran H.", rating: 4, text: "Busy on weekends. Go weekday mornings." },
    ],
    sarafaghar: [
      { name: "Gopal J.", rating: 5, text: "Chowk workshop. You can see the kada being engraved." },
      { name: "Neelam D.", rating: 4, text: "No AC theatre, but the rate is the rate." },
    ],
    rajwada: [
      { name: "Anjali V.", rating: 5, text: "Trial jewellery for pheras saved the actual set. Worth the making." },
      { name: "Kavya B.", rating: 5, text: "Hathphool sat perfectly. They measured my hand twice." },
    ],
    chandrahaas: [
      { name: "Isha N.", rating: 5, text: "Polki chandbalis have that Jaipur grey, not glassy CZ." },
      { name: "Rohit A.", rating: 4, text: "Lead time of three weeks for custom choker — they were clear upfront." },
    ],
    sonasutra: [
      { name: "Priya C.", rating: 5, text: "Office hoops under 5 grams. Finally jewellery I can wear to court." },
      { name: "Nidhi G.", rating: 4, text: "Small boutique. Call before you go." },
    ],
    aabharan: [
      { name: "Malika S.", rating: 5, text: "CAD sitting was 45 minutes. Ring came back exactly as sketched." },
      { name: "Arjun P.", rating: 4, text: "Four-week make is real. Do not expect walk-in custom." },
    ],
    meenakshi: [
      { name: "Savita R.", rating: 5, text: "Payal weight and making written on a paper chit, then on the bill. Trust." },
      { name: "Leela K.", rating: 4, text: "Oxidised restore took two days and came back even." },
    ],
    hiravatika: [
      { name: "Tanya D.", rating: 5, text: "Tennis bracelet stone chart is a spreadsheet. That is the standard." },
      { name: "Mohit V.", rating: 5, text: "Insurance papers prepared the same afternoon." },
    ],
    shringar: [
      { name: "Radhika J.", rating: 5, text: "Nath did not pinch. They mapped my nose in the mirror, not from a photo." },
      { name: "Smita W.", rating: 4, text: "Clip-on option is a blessing for the pheras only." },
    ],
    balsona: [
      { name: "Ankita F.", rating: 5, text: "Baby bangles so smooth I checked twice they were gold." },
      { name: "Rahul M.", rating: 4, text: "Gift box is ready. Resizing policy is printed." },
    ],
  },
};

function inr(n) {
  const v = Math.round(Number(n) || 0);
  return "₹" + v.toLocaleString("en-IN");
}

function inrDec(n) {
  const v = Number(n) || 0;
  return "₹" + v.toLocaleString("en-IN", { maximumFractionDigits: 0 });
}

function stars(rating) {
  const full = Math.floor(rating);
  const half = rating - full >= 0.4;
  return "★".repeat(full) + (half ? "½" : "") + "☆".repeat(Math.max(0, 5 - full - (half ? 1 : 0)));
}

function getShop(id) {
  const extra = Store.getShops();
  return extra.concat(RIVAAYAT.shops).find((s) => s.id === id);
}

function getProduct(id) {
  const extra = Store.getProducts();
  return extra.concat(RIVAAYAT.products).find((p) => p.id === id);
}

function allShops() {
  return RIVAAYAT.shops.concat(Store.getShops());
}

function allProducts() {
  return RIVAAYAT.products.concat(Store.getProducts());
}

function metalRate(purity) {
  const row = RIVAAYAT.rates.metals[purity] || RIVAAYAT.rates.metals["22K"];
  return row.perGram;
}

function priceBreakdown(product, overrides) {
  const p = Object.assign({}, product, overrides || {});
  const shop = getShop(p.shopId);
  const weight = Number(p.weight) || 0;
  const makingPct = p.makingPct != null ? Number(p.makingPct) : (shop ? shop.makingPct : 12);
  const wastagePct = p.wastagePct != null ? Number(p.wastagePct) : (shop ? shop.wastagePct : 2);
  const stone = Number(p.stoneCharges) || 0;
  const rate = metalRate(p.purity);
  const metalValue = weight * rate;
  const wastage = metalValue * (wastagePct / 100);
  const making = (metalValue + wastage) * (makingPct / 100);
  const gstMetal = (metalValue + wastage) * (RIVAAYAT.rates.gstMetal / 100);
  const gstMaking = making * (RIVAAYAT.rates.gstMaking / 100);
  const hallmark = RIVAAYAT.rates.hallmark;
  const total = metalValue + wastage + making + stone + gstMetal + gstMaking + hallmark;
  return {
    rate,
    weight,
    makingPct,
    wastagePct,
    metalValue,
    wastage,
    making,
    stone,
    gstMetal,
    gstMaking,
    hallmark,
    total,
  };
}

function productTotal(product) {
  return priceBreakdown(product).total;
}

const Store = {
  key: "rivaayat-v1",
  read() {
    try {
      return JSON.parse(localStorage.getItem(this.key)) || { shops: [], products: [], orders: [], wishlist: [], cart: [] };
    } catch (e) {
      return { shops: [], products: [], orders: [], wishlist: [], cart: [] };
    }
  },
  write(data) {
    localStorage.setItem(this.key, JSON.stringify(data));
  },
  getShops() {
    return this.read().shops || [];
  },
  getProducts() {
    return this.read().products || [];
  },
  getOrders() {
    return this.read().orders || [];
  },
  getWishlist() {
    return this.read().wishlist || [];
  },
  getCart() {
    return this.read().cart || [];
  },
  push(field, item) {
    const data = this.read();
    data[field] = data[field] || [];
    data[field].unshift(item);
    this.write(data);
  },
  toggleWish(id) {
    const data = this.read();
    data.wishlist = data.wishlist || [];
    const i = data.wishlist.indexOf(id);
    if (i >= 0) data.wishlist.splice(i, 1);
    else data.wishlist.push(id);
    this.write(data);
    return data.wishlist.indexOf(id) >= 0;
  },
  addCart(id) {
    const data = this.read();
    data.cart = data.cart || [];
    const row = data.cart.find((c) => c.id === id);
    if (row) row.qty += 1;
    else data.cart.push({ id, qty: 1 });
    this.write(data);
  },
  setCart(cart) {
    const data = this.read();
    data.cart = cart;
    this.write(data);
  },
};
